### ISSUE TITLE
ModuleNotFoundError: No module named 'bilateralfilter'

### ISSUE THREAD

**Issue by ChunmengLiu1** [rulixiang/wetr#1]
Thank you for a great job!
When I run the code met a problem "from bilateralfilter import bilateralfilter, bilateralfilter_batch
ModuleNotFoundError: No module named 'bilateralfilter' " in losses.py. I can't install it by pip and conda install command. Could you give me some advice? what is the "bilateralfilter "? How can I get it? Thank you very much.
I'm looking forward to hearing from you.

**Comment by sorrowyn** [comment]
https://github.com/zbf1991/RRM/tree/6d4191ce8938365a36be09aedb994ff9a35cb5e2
and then `python setup.py install`

**Comment by rulixiang** [comment]
Hey, @xinyuaning, thanks for your attention. @sorrowyn has kindly provided the solution and I hope this could help you. I will also update the README to show how to compile the python extension of the regularized loss.

**Comment by ChunmengLiu1** [comment]
Thanks!

---Original---
From: "Lixiang ***@***.***&gt;
Date: Wed, Mar 16, 2022 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rulixiang/afa] ModuleNotFoundError: No module named 'bilateralfilter' (Issue #1)




 
Hey, @xinyuaning, thanks for your attention. @sorrowyn has kindly provided the solution and I hope this could help you. I will also update the README to compile the python extension of the regularized loss.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
