### ISSUE TITLE
pseudo label

### ISSUE THREAD

**Issue by punk1** [rulixiang/wetr#4]
请问如何用 cam 生成  pseudo labels ，对应的代码在哪里，蟹蟹了。

**Comment by punk1** [comment]
https://github.com/rulixiang/afa/blob/85eeb3edf013f9f755fcc99e5a122b856dcd5840/datasets/transforms.py#L161
这个地方返回的 img_box  参与训练阶段了么

**Comment by rulixiang** [comment]
你好，抱歉现在才回复，img_box不参与训练，cam to pseudo label的代码请见：
https://github.com/rulixiang/afa/blob/430314067ca9ceb67ace08daddbc118e83411405/utils/camutils.py#L8

**Comment by zwyang6** [comment]
> 你好，抱歉现在才回复，img_box不参与训练，cam to pseudo label的代码请见：
> 
> https://github.com/rulixiang/afa/blob/430314067ca9ceb67ace08daddbc118e83411405/utils/camutils.py#L8

你好， 这个函数中img_box应该参与边界约束了吧

**Comment by rulixiang** [comment]
是，box之外的区域不计算分割损失
