### ISSUE TITLE
VOC Dateset

### ISSUE THREAD

**Issue by Yingw97** [rulixiang/wetr#5]
./afa-master/datasets/voc/cls_labels_onehot.npy
我想训练自己的数据集
请问这个cls_labels_onehot.npy文件是如何生成的？

**Comment by rulixiang** [comment]
你好，这个npy文件存储的是每张图像的类别标签（onehot形式），对自己的数据集可以自己写个脚本生成，并不是很难。

**Comment by zwyang6** [comment]
您好， 按照您提供的COCO的VOC 风格分割标注，读取出来的标签是4通道，放在你的coco训练代码里我这边是跑不通的。请问您是对该标注进行了进一步的处理吗，（例如将4通道信息转化为单通道）

**Comment by zwyang6** [comment]
> 您好， 按照您提供的COCO的VOC 风格分割标注，读取出来的标签是4通道，放在你的coco训练代码里我这边是跑不通的。请问您是对该标注进行了进一步的处理吗，（例如将4通道信息转化为单通道）

您提供的应该是未转化成VOC风格的labels吧，具体转换还得看您提供的repo代码！ 感谢

**Comment by shulan-s** [comment]
> 你好，这个npy文件存储的是每张图像的类别标签（onehot形式），对自己的数据集可以自己写个脚本生成，并不是很难。

您好，对于想处理一个新的数据集，应该怎么完成，能给一个步骤方案吗？非常感谢

**Comment by shulan-s** [comment]
> ./afa-master/datasets/voc/cls_labels_onehot.npy 我想训练自己的数据集 请问这个cls_labels_onehot.npy文件是如何生成的？

您好，您用自己的数据集成功了吗
