### ISSUE TITLE
No module named 'bilateralfilter'

### ISSUE THREAD

**Issue by zixijuns** [rulixiang/wetr#7]
When I try to run ```bash launch/run_sbatch_attn_reg.sh```
Traceback (most recent call last):
  File "scripts/dist_train_voc.py", line 21, in <module>
    from utils.losses import DenseEnergyLoss, get_aff_loss, get_energy_loss
  File "./utils/losses.py", line 9, in <module>
    from bilateralfilter import bilateralfilter, bilateralfilter_batch
ModuleNotFoundError: `No module named 'bilateralfilter'`

**Comment by rulixiang** [comment]
To use the `reg_loss`, you need to compile the extension module, see [here](https://github.com/meng-tang/rloss/tree/master/pytorch#build-python-extension-module) or #1 .

I now commented out the code related to the `reg_loss`. This repo should work finely now, but the performance should be slightly lower and close to 62.6% mIoU (see Table 2 in paper).
