### ISSUE TITLE
python 3.7 cuda 11.1 torch 1.8  got  error

### ISSUE THREAD

**Issue by wmrenr** [rulixiang/wetr#8]
![image](https://user-images.githubusercontent.com/43226404/172757957-b522371d-4cef-468e-b3a7-6e9ee33f7189.png)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I looked online for all possible solutions, to no avail.Do I have to be consistent with your version？

**Comment by tgyhhh** [comment]
Hello, have you solved this problem?
